# Generated by Django 4.0.3 on 2022-03-12 05:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singers',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('7e3ea373-ef6f-4ee8-b473-9d5036288cdc'), primary_key=True, serialize=False)),
                ('singer_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('7e3ea373-ef6f-4ee8-b473-9d5036288cdc'), primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=100)),
                ('singer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_song', to='myapp.singers')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
