# Generated by Django 4.0.3 on 2022-03-12 05:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('0d557670-3460-4690-b1a4-138b73e88604'), primary_key=True, serialize=False)),
                ('singer_name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('0d557670-3460-4690-b1a4-138b73e88604'), primary_key=True, serialize=False)),
                ('song_name', models.CharField(max_length=100)),
                ('singer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='singer_song', to='myapp.singer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='songs',
            name='singer_name',
        ),
        migrations.DeleteModel(
            name='Singers',
        ),
        migrations.DeleteModel(
            name='Songs',
        ),
    ]
