# Generated by Django 4.0.3 on 2022-03-12 07:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_singer_song_remove_songs_singer_name_delete_singers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='song',
            name='singer_name',
        ),
        migrations.AddField(
            model_name='song',
            name='singer_name',
            field=models.ManyToManyField(related_name='singer_song', to='myapp.singer'),
        ),
        migrations.AlterField(
            model_name='song',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
