# Generated by Django 4.0.3 on 2022-03-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_song_movie_name_movie_song_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='song_name',
        ),
        migrations.AddField(
            model_name='song',
            name='movie_name',
            field=models.ManyToManyField(related_name='song_name1', to='myapp.movie'),
        ),
    ]
